### ISSUE TITLE
Option to turn off fuzzy Search

### ISSUE THREAD

**Issue by gyaaniguy** [Wox-launcher/Wox#1845]
Right now searching for files gives very weird results.

**Comment by lances101** [comment]
What version are you using?
Examples / Screenshots?

**Comment by harrynull** [comment]
![tim 20180120222050](https://user-images.githubusercontent.com/7413706/35184412-40022d6e-fe30-11e7-9928-bf4bd1c008ca.png)
I don't know how Photoshop and Windows Mobility Center are related.

**Comment by lances101** [comment]
@harrynull, not a bug
Wox fuzzy matches the application name and description. Here is how it matches it in this situation:

> adjust dis`p`lay brig`h`tness, v`o`lume, power op`t`i`o`n`s`, and ot`h`er c`o`ommonly used mobile `p`c settings

As you can see, the letters corresponding to "photoshop" are actually in the description of the application.

**Comment by harrynull** [comment]
@lances101 However, in the reality, a user will never use "photoshop" to search "Windows Mobility Center". I'd say it's more like a bug than expected behavior to a normal user.
Could you consider change the behavior of search from anywhere in the description to continuous letters, or even only match the title?

**Comment by gyaaniguy** [comment]
Agreed with harry null. Would suggest having an option to turn off fuzzy.

**Comment by lances101** [comment]
This is not as straightforward as it may look and requires more discussion.

What is your suggestion for this then?
Turning fuzzy completely?
Not fuzzy matching descriptions?
Setting a a max distance for fuzzy matching? If yes, then what do you consider sensible?

**Comment by harrynull** [comment]
I'd say not to completely turn it off, but to optimize it. For example, only allow continuous letters to be considered match.

**Comment by gyaaniguy** [comment]
Not fuzzy matching descriptions?   
- I think this could be the simplest to implement, and effective way forward.

**Comment by thespad** [comment]
Or at least prioritise results with continuous matches and then order by "fuzziness". For example right now if I search for "PAYE" I get this:

![capture](https://user-images.githubusercontent.com/8425502/35529251-65e607e0-0528-11e8-94a3-9534c5082632.PNG)

When I don't want any of the first 3 results, otherwise I would have searched using a term that was more suited to them; but if, for example, I'd made a (very bad) typo and actually meant to type "Player" then it's useful to have those results show up after the ones that are more likely to be correct.

**Comment by Lomacar** [comment]
I agree with TheSpad that search results need better ordering, not disabling. With the current over-aggressive fuzzy searching Wox's search results border on idiotic. If I have a particular file that I am searching for with a completely unique name I expect it to be first on the list when I type the exact name, not a whole bunch of random junk that happens to have those letters distributed in their descriptions or file paths.

In my opinion this is the number 1 usability issue with Wox. I don't know how anyone could use Wox and not be constantly frustrated about the current behaviour.

Really, there should be an issue about ordering of Wox results, and maybe there is, but I found this one first, so I will just say a bit more here. (I don't think there should be an option to disable fuzzy search anyway. That is not the solution to the problem.)

Right now, if I do a search for "\temp", is the first result "C:\temp", like you would expect, or any other temp folder? No. This is what I mean by "idiotic". There appears to be literally 0 intelligence in the ordering of search results. It appears that fuzzy search just matches "\temp" in the first place it finds it, which is indeed "c:\temp", but it doesn't stop there. It displays EVERY folder that has "temp" in the path name, and organizes the results alphabetically (or probably just in the order they were found in the index), so in my case, Wox first lists a million ".bin" subfolders inside "c:\temp", then ".svn" folders in other locations, then folders names "00" and "01"... Actually, none of the search results are simply a folder named "temp". So as it is, Wox is useless for searching for folder names that have many subfolders, unless there is something better I can type that I don't know of.

OK, when I check Search Everything, I see that sorts things the exact same way, so maybe my real issue is with Everything? Still, couldn't Wox sort the results? If I sort the results in Everything by the Path column then "C:\temp" is at the top.

**Comment by strat0caster** [comment]
Was playing around with the source code and found a way to mitigate the aggressive fuzzy search a bit.

The problem seems to be that whenever fuzzy search is used, there isn't very strict judging about whether the result is a good match. A lot of comparisons regarding `Score`s only compares them to 0, meaning that anything that contains the same characters as in the `query` in the same order will be considered a "good match".

My half-ass solution is to go to `Wox.Infrastructure`, in `FuzzyMatcher.cs`, find the method `CalScore` and add one line `score = score - 30;` just before `return score`. This will make the score of a lot of nonsense results below 0 and clean up the search results a bit, but things like "CTR" will still give you "Control Panel" so some level of functionality is still maintained.

Some better ways I can think of to do this:
1. Optimize the way Score is calculated. Take the PAYE example from @TheSpad , the `score = score -30` method would probably get rid of the desired results as well. 
2. Adding a "Fuzzy level" slider or sth like that in the general settings tab or for specific plugins. 
3. Optimize the way FuzzyMatcher is designed, which I know is going to be a huge project on its own. 

I'm sorry to say that I'm neither smart nor an experienced coder to do those things elegantly and bug-free-ly (I'm a semiconductor optoelectronics grad student and just wanted to create a toy plugin to convert some units as a weekend project). So I guess these can be considered as suggestions? And please forgive me if I expressed sth poorly or used wrong programming terms.

**Comment by Cdddo** [comment]
Seriously this is the main usability issue on Wox. It drives me crazy that I can't find things easily because the results are cluttered with completely irrelevant results. This single issue probably drives a lot of people away from Wox because it's not obvious what it is doing, and otherwise Wox is a good tool. There's more than a handful of issues opened here because people "can't find anything" "doesn't work" "confused" all caused by this problem, see #2351 #2246 #2304 #2479 

I can't imagine any reason why the current matching behavior makes any sense on program descriptions. Maybe it makes sense in Chinese where a character carries more meaning than a letter in most western languages.

In my opinion there's several separate actions that even individually would make for a huge improvement:

1. Description matches should rank lower than name matches
2. There should be a setting to disable fuzzy matching to **descriptions**, forcing exact matches, or altogether disabling matching to descriptions.
3. There should also be a setting to customize the fuzzy search to a certain amount of continuous letters, something like 3 or 4 letters could be a good default; since it would exclude most of the issues like in the "photoshop" example above, as well as short articles that are often 2/3 letters (a, or, if, the, is...) and add little semantic value to the search. 
4. Folders should be sorted to the best match with the shortest paths.
5. System folders should be excluded by default, and be searchable with a keyword (this might not be so necessary if the above is fixed, but at the moment its a good way to get rid of a lot of clutter)

**Comment by Lomacar** [comment]
Yes, an option to turn off matching description would be an EASY FIX and VERY HELPFUL!

**Comment by Lomacar** [comment]
I have a folder called "podcast" in my Downloads folder. Previously it wasn't showing up in the first screen of results if I searched for "podcast". Now for some reason it is, but it is buried at the bottom of 14 entirely useless results based on file description. Are those ever useful for anyone? If I try to narrow the results by searching for "down podcast" it doesn't show any results! Where is fuzzy search when you actually need it?!?!

**Comment by jjw24** [comment]
Hey guys, late to the party, but your frustration is now addressed in PR https://github.com/Wox-launcher/Wox/pull/2611

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, please let met know

**Comment by bao-qian** [comment]
fuzzy match has been rewrite using advanced string algorithm, 
try new release https://github.com/Wox-launcher/Wox/releases
let me know if it still not fixed
