### ISSUE TITLE
[bug] Crash on Win+R

### ISSUE THREAD

**Issue by ckesc** [Wox-launcher/Wox#206]
1. Press `Win+R`
2. Enter `dir`
3. Hit `Enter`
4. Crash!

**Comment by qianlifeng** [comment]
Can't reproduce this bug. Pls try the latest version of Wox.

**Comment by ckesc** [comment]
It seems that it was solved

**Comment by matteocontrini** [comment]
I'm having this problem now with v1.0.2

**Comment by matteocontrini** [comment]
Still the same problem with v1.1.0. Can you handle that crash in some way and log the exception or whatever it is? Now the program terminates with the Windows dialog "Wox has stopped working"

**Comment by qianlifeng** [comment]
i will look into this.
