### ISSUE TITLE
"Everything Client is not running" error appears 

### ISSUE THREAD

**Issue by shwetm98** [Wox-launcher/Wox#3096]
<img width="606" alt="Error wox" src="https://user-images.githubusercontent.com/47413792/86427416-c7a32500-bd07-11ea-8b45-2d832d356b1a.png">

**Comment by fgimian** [comment]
Ensure you've installed using the Wox Full installer and then start the app called **Search Everything**.

It seems Wox is using the Everything app as the engine for searching files, so it will need to be running alongside Wox.

Cheers
Fotis

**Comment by tzakrajs** [comment]
It seems like Search Everything can start after Wox, which causes Wox to not start the Everything Client until Wox is restarted. Is Wox supposed to be restarting the Everything Client periodically if it is not running?

**Comment by davl3232** [comment]
I had this issue just after installing with `wox-full-installer*.exe` and it solved itself after I restarted once.

It only asked for disk permissions after the restart, so that might be the cause.

**Comment by samsungstark** [comment]
I encountered this after installing https://github.com/Wox-launcher/Wox/releases/download/v1.4.1196/Wox-Full-Installer.1.4.1196.exe from a fresh install

**Comment by Slesa** [comment]
What exactly is this 'search everything'? I can only find an SDK dll, but nothing to run? The plugin with that name is enabled.

**Comment by Afonix** [comment]
I restarted mine and the problem was solved 

Just tap Wox on the Wox search bar and "Restart Wox "would show up
Cick on it

**Comment by notfresh** [comment]
Me too, I use the full installer and try to search some files, but wox tells me "everyting client is not running", 

I open the everything client myself mannually and so I can use it as I expect.

**Comment by gendaili** [comment]
Tried restart wox but still show the everything clien not start, even the everything is running.
![Screenshot 2024-09-06 093251](https://github.com/user-attachments/assets/31c47a27-3e6b-410b-8129-e4822f597429)

**Comment by aubreyz** [comment]
Same here. Used full installer even though I really wanted portable. Despite that still message as above and even after relating many times. 
I don't need a long debugging curve for new apps especially when developers seem to have abandoned, so I uninstalled it and will go back to using everything by itself which seems to offer just as much without the hassle
