### ISSUE TITLE
taking too much cpu resources

### ISSUE THREAD

**Issue by ydv-sahitya** [Wox-launcher/Wox#3349]
taking too much resource. I am using i7 8 gen in my laptop. it is 12 core cpu.  when I open to search in the Wox it goes up to 50 % . this is too much. 

![wox](https://user-images.githubusercontent.com/37513489/106358136-385b0000-6330-11eb-8a55-6e59c0d3ed11.PNG)

when in the background Wox using 17% of my resource. I am going to uninstall
![without using](https://user-images.githubusercontent.com/37513489/106358216-b0c1c100-6330-11eb-9e99-99e5f9c2b47f.PNG)
 for now.

**Comment by ydv-sahitya** [comment]
![wox_report](https://user-images.githubusercontent.com/37513489/106381020-0606dc80-63dc-11eb-9173-d573e3ffbb84.PNG)
Hi I want  to add up something  little more ,  I am using Wox in my second laptop . this laptop quite old. Wox seems working fine here. not taking too much resources. 

when I search something it uses 10% cpu resource.  

And when I am not using it . It goes down to 1% or 0% sometimes. 

here in my laptop I have amd A7 series chip. 

  I just want to add up In my second device Wox working fine.

**Comment by zany130** [comment]
this happens to me when it uses everything to search for something. cpu usage stays high even after hiding wox. I need to restart wox to get it to stop killing my cpu. 11gen intel i7

EDIT: found out its not everything causing this, its the programs plugin
and it seems to have no high cpu usage with flow-launcher a fork of wox

**Comment by L4ys** [comment]
I found the root cause is because there're some UWP programs which contains a long description:

![image](https://user-images.githubusercontent.com/5360374/109409970-de526680-79d1-11eb-8641-b99f1dbc3e70.png)

and `StringMatcher.FuzzySearch` is very slow when matching these strings

**Comment by L4ys** [comment]
@jjw24 Do you mind porting flow-launcher's StringMatcher back to Wox? this should solve the problem.

**Comment by chuckdee68** [comment]
This is still happening. It's causing me to rethink Wox. @L4ys - can't you port it back to Wox and submit a PR?

**Comment by ak47watts** [comment]
so... why not just use flow launcher?         ¯\_(ツ)_/¯
